os:
  edit: 'nvim -- {{filename}}'
  editAtLine: 'nvim +{{line}} -- {{filename}}'
  editAtLineAndWait: 'nvim +{{line}} -- {{filename}}'
  editInTerminal: true
  open: 'nvim -- {{filename}}'
  openDirInEditor: 'nvim {{dir}}'
