[mgr]
ratio = [2, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "none"
show_hidden = true 
show_symlink = true
scrolloff = 5

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""
image_delay = 30
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "macos" },
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = 'mpv "%*"', orphan = true, for = "windows" },
]
open = [
  { run = 'open "$@"', desc = "Open", for = "macos" },
]

[open]
rules = [
  { name = "*.md", use = [ "edit" ] },
  { name = "*.txt", use = [ "edit" ] },
  { name = "*.lua", use = [ "edit" ] },
  { name = "*.js", use = [ "edit" ] },
  { name = "*.ts", use = [ "edit" ] },
  { name = "*.tsx", use = [ "edit" ] },
  { name = "*.jsx", use = [ "edit" ] },
  { name = "*.py", use = [ "edit" ] },
  { name = "*.rs", use = [ "edit" ] },
  { name = "*.go", use = [ "edit" ] },
  { name = "*.c", use = [ "edit" ] },
  { name = "*.cpp", use = [ "edit" ] },
  { name = "*.h", use = [ "edit" ] },
  { name = "*.java", use = [ "edit" ] },
  { name = "*.rb", use = [ "edit" ] },
  { name = "*.sh", use = [ "edit" ] },
  { name = "*.bash", use = [ "edit" ] },
  { name = "*.zsh", use = [ "edit" ] },
  { name = "*.vim", use = [ "edit" ] },
  { name = "*.css", use = [ "edit" ] },
  { name = "*.scss", use = [ "edit" ] },
  { name = "*.html", use = [ "edit" ] },
  { name = "*.xml", use = [ "edit" ] },
  { name = "*.yaml", use = [ "edit" ] },
  { name = "*.yml", use = [ "edit" ] },
  { name = "*.toml", use = [ "edit" ] },
  { name = "*.conf", use = [ "edit" ] },
  { name = "*.ini", use = [ "edit" ] },
  { name = "*/", use = [ "edit", "open" ] },
  { mime = "text/*", use = [ "edit" ] },
  { mime = "image/*", use = [ "open" ] },
  { mime = "video/*", use = [ "play", "open" ] },
  { mime = "audio/*", use = [ "play" ] },
  { mime = "inode/x-empty", use = [ "edit" ] },
  { mime = "application/json", use = [ "edit" ] },
  { mime = "*/javascript", use = [ "edit" ] },
  { mime = "*", use = [ "open" ] },
]

[tasks]
micro_workers = 10
macro_workers = 25
bizarre_retry = 5
image_alloc = 536870912
image_bound = [ 0, 0 ]
suppress_preload = false
